CC = gcc
CFLAGS = -ansi -Wall -pedantic
single_blank: single_blank.c
	$(CC) single_blank.c $(CFLAGS) -o single_blank

clean:
	rm -f character_countCC = gcc
CFLAGS = -ansi -Wall -pedantic
single_blank: single_blank.c
	$(CC) single_blank.c $(CFLAGS) -o single_blank

clean:
	rm -f single_blank