CC = gcc
CFLAGS = -ansi -Wall -pedantic
character_arrays_revised: character_arrays_revised.c
	$(CC) character_arrays_revised.c $(CFLAGS) -o character_arrays_revised

clean:
	rm -f character_arrays_revised